#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
DATE_KEY="${1:-$(TZ=Asia/Seoul date +%F)}"
SRC_MD="${2:-$ROOT_DIR/reports/md/LG_Global_D2C_Weekly_Intelligence_${DATE_KEY}_R2_16country.md}"
OUT_MD_EN="$ROOT_DIR/reports/md/LG_Global_D2C_Weekly_Intelligence_${DATE_KEY}_en.md"

OUT_HTML_DIR="$ROOT_DIR/reports/html/$DATE_KEY"
OUT_HTML="$OUT_HTML_DIR/LG_Global_D2C_Weekly_Intelligence_${DATE_KEY}_R2_16country.html"
OUT_HTML_EN="$OUT_HTML_DIR/index_en.html"
OUT_PDF_DIR="$ROOT_DIR/reports/pdf"
OUT_PDF="$OUT_PDF_DIR/LG_Global_D2C_Weekly_Intelligence_${DATE_KEY}_R2_16country.pdf"
LATEST_PDF="$ROOT_DIR/reports/pdf/LG_Global_D2C_Weekly_Intelligence_latest.pdf"
OUT_META="$OUT_HTML_DIR/metadata.json"
MANIFEST_FILE="$ROOT_DIR/reports/html/manifest.json"
LATEST_DIR="$ROOT_DIR/reports/html/latest"
LATEST_HUB="$LATEST_DIR/hub.html"
ROOT_HTML_INDEX="$ROOT_DIR/reports/html/index.html"
HTML_PDF_DIR="$ROOT_DIR/reports/html/pdf"
HTML_MD_DIR="$ROOT_DIR/reports/html/md"

mkdir -p "$OUT_HTML_DIR" "$OUT_PDF_DIR" "$LATEST_DIR" "$HTML_PDF_DIR" "$HTML_MD_DIR"
rm -f "$LATEST_DIR/main.html"

if ! command -v node >/dev/null 2>&1; then
  echo "node command not found" >&2
  exit 1
fi
if ! command -v playwright >/dev/null 2>&1; then
  echo "playwright command not found" >&2
  exit 1
fi

node "$ROOT_DIR/scripts/render_professional_report.mjs" "$SRC_MD" "$OUT_HTML" "ko"
cp "$OUT_HTML" "$OUT_HTML_DIR/index.html"
bash "$ROOT_DIR/scripts/translate_report_to_english.sh" "$SRC_MD" "$OUT_MD_EN"
node "$ROOT_DIR/scripts/render_professional_report.mjs" "$OUT_MD_EN" "$OUT_HTML_EN" "en"

node "$ROOT_DIR/scripts/extract_report_metadata.mjs" "$SRC_MD" "$DATE_KEY" "$OUT_META"
node "$ROOT_DIR/scripts/update_report_manifest.mjs" "$ROOT_DIR/reports/html" "$MANIFEST_FILE"
node "$ROOT_DIR/scripts/render_reports_hub.mjs" "$MANIFEST_FILE" "$LATEST_HUB"

cat > "$OUT_HTML_DIR/share.html" <<HTML
<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Share Links</title><style>body{margin:0;background:#f3f6fa;color:#0f172a;font:16px/1.55 "Noto Sans KR",-apple-system,sans-serif}.wrap{max-width:980px;margin:40px auto;padding:0 20px}.card{background:#fff;border:1px solid #d9e2ec;border-radius:16px;padding:28px;box-shadow:0 10px 30px rgba(15,23,42,.08)}h1{margin:0 0 10px;font-size:30px}p{margin:8px 0 0;color:#334155}.links{margin-top:22px;display:grid;gap:12px}a{display:block;padding:14px 16px;border-radius:10px;border:1px solid #c7d6e6;text-decoration:none;color:#0b4f88;background:#f8fbff;font-weight:700}a:hover{background:#eef6ff}.meta{margin-top:18px;font-size:13px;color:#64748b}</style></head><body><div class="wrap"><div class="card"><h1>LG Global D2C Weekly Intelligence</h1><p>Week: ${DATE_KEY} · Share-ready links</p><div class="links"><a href="./index.html">Open This Week HTML Report</a><a href="../latest/hub.html">Open Weekly Hub (History + Compare)</a><a href="../latest/hub_en.html">Open Weekly Hub (English)</a><a href="../pdf/LG_Global_D2C_Weekly_Intelligence_${DATE_KEY}_R2_16country.pdf">Download This Week PDF</a><a href="../pdf/LG_Global_D2C_Weekly_Intelligence_latest.pdf">Download Latest PDF</a></div><div class="meta">Generated by build_publishable_report.sh</div></div></div></body></html>
HTML

URL=$(python3 - <<PY
import pathlib, urllib.parse
p=pathlib.Path(r'''$OUT_HTML''').resolve()
print('file://' + urllib.parse.quote(str(p)))
PY
)

if ! playwright pdf --paper-format A4 --channel chrome "$URL" "$OUT_PDF"; then
  echo "warning: playwright pdf generation failed, trying fallback from latest pdf" >&2
  if [[ -f "$LATEST_PDF" ]]; then
    cp "$LATEST_PDF" "$OUT_PDF"
  else
    echo "failed to generate pdf and no fallback latest pdf found" >&2
    exit 1
  fi
fi

cp "$OUT_HTML_DIR/index.html" "$LATEST_DIR/index.html"
cp "$OUT_HTML_EN" "$LATEST_DIR/index_en.html"
cp "$OUT_HTML_DIR/share.html" "$LATEST_DIR/week-share.html"
cp "$OUT_PDF" "$LATEST_PDF"
cp "$OUT_PDF" "$HTML_PDF_DIR/$(basename "$OUT_PDF")"
cp "$OUT_PDF" "$HTML_PDF_DIR/LG_Global_D2C_Weekly_Intelligence_latest.pdf"
cp "$SRC_MD" "$HTML_MD_DIR/$(basename "$SRC_MD")"
cp "$OUT_MD_EN" "$HTML_MD_DIR/$(basename "$OUT_MD_EN")"
cp "$MANIFEST_FILE" "$LATEST_DIR/manifest.json"
cat > "$ROOT_HTML_INDEX" <<'HTML'
<!doctype html>
<html lang="ko">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta http-equiv="refresh" content="0; url=./latest/hub.html" />
  <title>LG D2C Weekly Main</title>
  <style>
    body{margin:0;background:#f5f8fc;color:#0f172a;font:16px/1.55 "Noto Sans KR",-apple-system,sans-serif}
    .wrap{max-width:760px;margin:60px auto;padding:0 20px}
    .card{background:#fff;border:1px solid #d9e2ec;border-radius:14px;padding:22px;box-shadow:0 8px 22px rgba(15,23,42,.08)}
    a{color:#0b4f88;font-weight:700}
  </style>
</head>
<body>
  <div class="wrap">
    <div class="card">
      <h1>LG Global D2C Weekly Intelligence</h1>
      <p>메인 페이지로 이동합니다.</p>
      <p><a href="./latest/hub.html">자동 이동이 되지 않으면 이 링크를 클릭하세요.</a></p>
    </div>
  </div>
</body>
</html>
HTML

cat > "$LATEST_DIR/share.html" <<'HTML'
<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Share Links</title><style>body{margin:0;background:#f3f6fa;color:#0f172a;font:16px/1.55 "Noto Sans KR",-apple-system,sans-serif}.wrap{max-width:980px;margin:40px auto;padding:0 20px}.card{background:#fff;border:1px solid #d9e2ec;border-radius:16px;padding:28px;box-shadow:0 10px 30px rgba(15,23,42,.08)}h1{margin:0 0 10px;font-size:30px}p{margin:8px 0 0;color:#334155}.links{margin-top:22px;display:grid;gap:12px}a{display:block;padding:14px 16px;border-radius:10px;border:1px solid #c7d6e6;text-decoration:none;color:#0b4f88;background:#f8fbff;font-weight:700}a:hover{background:#eef6ff}.meta{margin-top:18px;font-size:13px;color:#64748b}</style></head><body><div class="wrap"><div class="card"><h1>LG Global D2C Weekly Intelligence</h1><p>Latest share page</p><div class="links"><a href="./hub.html">Open Weekly Hub (History + Compare)</a><a href="./hub_en.html">Open Weekly Hub (English)</a><a href="./index.html">Open Latest HTML Report</a><a href="../pdf/LG_Global_D2C_Weekly_Intelligence_latest.pdf">Download Latest PDF</a></div><div class="meta">Generated by build_publishable_report.sh</div></div></div></body></html>
HTML

echo "HTML: $OUT_HTML_DIR/index.html"
echo "Share: $OUT_HTML_DIR/share.html"
echo "PDF: $OUT_PDF"
echo "Hub: $LATEST_HUB"
echo "Main: $ROOT_HTML_INDEX"
